### PR TITLE
[Bug/42097] relations/notifications even when the oauth information is not complete

### PR DESCRIPTION
**Pull request by kiranparajuli589**
### Description
OP#42097,
- do not fetch work packages if the admin config is not ok
- do not fetch notifications if the admin config is not ok

### Related
https://community.openproject.org/projects/nextcloud-integration/work_packages/42097

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
@SwikritiT I can see the no connection message below the icon.
Screenshot from 2022-04-29 09-58-33
Screenshot from 2022-04-29 09-59-02

can you check with the latest `nextcloud/server`? there were some theme-related fixes recently.

**Review by individual-it — CHANGES_REQUESTED** [review]
I tried with NC 23 and I cannot see the error text

**Comment by kiranparajuli589** [comment]
hmm, it was also not showing for our docker setup. I've fixed the pr now to show the proper connection error message. @SwikritiT  @individual-it can you please re review.

**Review by individual-it — COMMENTED** [review]
please rebase on master to get your state refactoring

**Review by SwikritiT — COMMENTED** [review]
I can see the error message now. LGTM :+1:

**Review by individual-it — APPROVED** [review]

**Review by individual-it — CHANGES_REQUESTED** [review]
according to the meeting on 5.5.2022
- when admin changes any setting all oauth tokens in NC are deleted
- add a confirmation dialog for the admin before changing any oauth settings, saying that after changing the settings every user will have to reconnect

**Comment by kiranparajuli589** [comment]
> according to the meeting on 5.5.2022
> 
> * when admin changes any setting all oauth tokens in NC are deleted
> * add a confirmation dialog for the admin before changing any oauth settings, saying that after changing the settings every user will have to reconnect

This will be implemented in a separate PR.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
