### PR TITLE
Make search input sticky while scrolling

### PR DESCRIPTION
**Pull request by SagarGi**
### Description

This PR makes changes to make the search input for searching workpackages `sticky` while scrolling.

OP#42136 https://community.openproject.org/projects/nextcloud-integration/work_packages/42136/activity

### CODE REVIEW

**Review by SwikritiT — CHANGES_REQUESTED** [review]
The list should also scroll up when the new work package gets added so that we can have a visual confirmation that it got "added". Right now we can't see the new work package that got added unless we scroll up again. 

https://user-images.githubusercontent.com/41103328/172315614-a01bf794-a98a-4aa9-8426-d3c308c916a8.mp4

Also for some reason, the search list is not cleared when the search keyword is deleted but I need to check if that's the problem of this PR or it's a bug

**Review by kiranparajuli589 — CHANGES_REQUESTED** [review]

**Review by SwikritiT — APPROVED** [review]
LGTM

**Comment by kiranparajuli589** [comment]
code looks good, I'll add the unit tests for this tomorrow.

**Comment by SwikritiT** [comment]
@SagarGi https://github.com/nextcloud/integration_openproject/pull/135 this has been merged so I'll close this PR

**Pull request closed without merging**
