### PR TITLE
Update some npm pkgs and make adjustments

### PR DESCRIPTION
**Pull request by julien-nc**
@nextcloud/axios @nextcloud/eslint-config @nextcloud/router @nextcloud/stylelint-config @nextcloud/vue @nextcloud/webpack-vue-config vue vue-material-design-icons @nextcloud/dialogs and vue-template-compiler were updated.
Some small adjustments were needed.

@vue/cli-plugin-unit-jest was not updated, just in case.
Anyway the jest snapshots probably need to be regenerated.

### CODE REVIEW

**Comment by SwikritiT** [comment]
I've updated the snapshots some of the tests are still failing, I'll take a look on why they are failing

**Comment by SwikritiT** [comment]
with nextcloud-23 on admin-settings section, the dialog is not shown. 

https://user-images.githubusercontent.com/41103328/229729778-1abafebc-ad87-4d27-8a12-3ef332cd1b9e.mp4

**Comment by julien-nc** [comment]
Hey @SwikritiT, I managed to upgrade everything except
* `@nextcloud/dialogs`
* `@vue/cli-plugin-unit-jest`
* `@vue/test-utils`
* `@vue/vue2-jest`

To make sure we could properly update some pkgs, i had to set a fixed version for the `@vue/*` ones so we could have a coherent dependency tree by running `npm update`.

Sorry i started from scratch and force-pushed on this branch. Could you update the snapshots again?

**Comment by SwikritiT** [comment]
> Hey @SwikritiT, I managed to upgrade everything except
> 
> * `@nextcloud/dialogs`
> * `@vue/cli-plugin-unit-jest`
> * `@vue/test-utils`
> * `@vue/vue2-jest`
> 
> To make sure we could properly update some pkgs, i had to set a fixed version for the `@vue/*` ones so we could have a coherent dependency tree by running `npm update`.
> 
> Sorry i started from scratch and force-pushed on this branch. Could you update the snapshots again?

Okay, I'll update the snapshots. Thank you.

**Comment by SwikritiT** [comment]
Did some manual testing with different versions of NC, no problem in UI

**Pull request merged**
