### PR TITLE
[docs] update developer documentation

### PR DESCRIPTION
**Pull request by kiranparajuli589**
- add missing `cd` step after cloning
- state `node`, `npm`, `docker` version requirements

### CODE REVIEW

**Review by SwikritiT — APPROVED** [review]
LGTM

**Comment by individual-it** [comment]
CC @wielinde

**Comment by individual-it** [comment]
should we mention the minimum docker-compose and docker versions?

**Comment by kiranparajuli589** [comment]
> should we mention the minimum docker-compose and docker versions?

yes. I've added it.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
