### PR TITLE
[OP#45841] correct OP thumbnail in search

### PR DESCRIPTION
**Pull request by individual-it**
Related work package: [OP#45841]  https://community.openproject.org/projects/nextcloud-integration/work_packages/45841/activity?query_id=3513

## Before:
content

### NC- Master
*light theme* 

Screenshot from 2023-01-23 13-00-21

*dark theme*

Screenshot from 2023-01-23 13-00-39

### NC- stable25
*light theme* 

Screenshot from 2023-01-23 13-15-56

*dark theme*

Screenshot from 2023-01-23 13-15-39

### NC- stable24
*light theme* 

Screenshot from 2023-01-23 14-16-03

*dark theme*
Screenshot from 2023-01-23 14-16-20

### CODE REVIEW

**Review by individual-it — COMMENTED** [review]
LGTM!

**Comment by SagarGi** [comment]
for some reason i am getting this on `stable25`. 
Screenshot from 2023-01-23 17-20-06

But working fine on `stable24`.

**Comment by SwikritiT** [comment]
> for some reason i am getting this on `stable25`. Screenshot from 2023-01-23 17-20-06
> 
> But working fine on `stable24`.

It worked for me. I'll check it again.

**Comment by SwikritiT** [comment]
@SagarGi It's working for me. Can you check again? 
Screenshot from 2023-01-24 09-54-55

**Comment by SagarGi** [comment]
> > for some reason i am getting this on `stable25`. Screenshot from 2023-01-23 17-20-06
> > But working fine on `stable24`.
> 
> It worked for me. I'll check it again.

@SwikritiT This problem occur when we fresh install and the theme is on system-default-theme. May be the code broke which gave exception and the pop up appeared. But after i changed the theme to other themes it seems to work fine.

**Comment by SwikritiT** [comment]
> > > for some reason i am getting this on `stable25`. Screenshot from 2023-01-23 17-20-06
> > > But working fine on `stable24`.
> > 
> > 
> > It worked for me. I'll check it again.
> 
> @SwikritiT This problem occur when we fresh install and the theme is on system-default-theme. May be the code broke which gave exception and the pop up appeared. But after i changed the theme to other themes it seems to work fine.

Thanks I'll fix it

**Comment by SwikritiT** [comment]
@SagarGi should be fixed by a recent commit now. please check again

**Review by SagarGi — APPROVED** [review]
I checked working fine now. LGTM :+1:

**Pull request merged**
