### PR TITLE
[#51662] Update Nextcloud integration description in NC app store

### PR DESCRIPTION
**Pull request by dominic-braeunlein**
[OP#51662](https://community.openproject.org/work_packages/51662)

Updates the app description and screenshot to represent the new **"Create work packages in Nextcloud"** feature.

### CODE REVIEW

**Comment by SagarGi** [comment]
hi @dominic-braeunlein A similar PR that i  have made has been already merged. https://github.com/nextcloud/integration_openproject/pull/550

**Comment by dominic-braeunlein** [comment]
Thank you @SagarGi. I changed the target to `release/2.5 and added the additional app description to the readme too.

**Review by psatyal — APPROVED** [review]
LGTM

**Comment by SagarGi** [comment]
Hi @dominic-braeunlein https://github.com/nextcloud/integration_openproject/pull/551/files#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9eR18 i have added a similar points link you have added as `Create work packages directly in Nextcloud`. Can you decide a select on among these two? and then we can merge this PR.

**Comment by SagarGi** [comment]
LGTM :+1: But DCO seems to be failing since the commit is not signed off:

**Review by SagarGi — APPROVED** [review]

**Review by individual-it — APPROVED** [review]

**Pull request merged**
